use sakila;
select * from film;
select * from film_category;
select * from category;

-- 1. List the number of films per category.
SELECT * FROM film;
SELECT * FROM film_category;
SELECT * FROM category;

SELECT c.name AS Category, COUNT(film_category.film_id) AS Number_of_Films
FROM category c
JOIN film_category ON c.category_id = film_category.category_id
GROUP BY c.name
ORDER BY Number_of_Films DESC;

-- 2. Retrieve the store ID, city, and country for each store.
SELECT * FROM store;

SELECT s.store_id, ci.city, co.country
FROM store s
JOIN address a ON s.address_id = a.address_id
JOIN city ci ON a.city_id = ci.city_id
JOIN country co ON ci.country_id = co.country_id;

-- 3. Calculate the total revenue generated by each store in dollars.
SELECT s.store_id, SUM(p.amount) AS Total_Revenue
FROM payment p
JOIN rental r ON p.rental_id = r.rental_id
JOIN inventory i ON r.inventory_id = i.inventory_id
JOIN store s ON i.store_id = s.store_id
GROUP BY s.store_id
ORDER BY Total_Revenue DESC;

-- 4. Determine the average running time of films for each category.
SELECT c.name AS Category, AVG(f.length) AS Average_Length
FROM category c
JOIN film_category fc ON c.category_id = fc.category_id
JOIN film f ON fc.film_id = f.film_id
GROUP BY c.name
ORDER BY Average_Length DESC;